export const addFilterButton = '[data-test-subj="addFilter"]';
export const filterSuggestionList = '[data-test-subj="filterFieldSuggestionList"]';
export const filterOperatorList = '.euiForm .euiFlexGroup--responsive [data-test-subj="filterOperatorList"] [data-test-subj="comboBoxInput"]';
export const filterParams = '[data-test-subj="filterParams"]';
export const saveFilterButton = '[data-test-subj="saveFilter"]';
export const stablishedFilter = '[data-test-subj="filter filter-enabled filter-key-rule.level filter-value-7 filter-unpinned"';
export const pinFilterAction = '[data-test-subj="pinFilter"]';
export const selectedOperator = '[title="is"]';
export const pinnedFilter= '[data-test-subj="filter filter-enabled filter-key-rule.level filter-value-7 filter-pinned"]';
export const eventsButton = '//*[contains(@class,"euiTabs")]//*[contains(text(),"Events")]';
export const removeFilterButton = '//*[contains(@class,"euiContextMenuPanel")]//*[contains(text(),"Delete")]';