import { When } from 'cypress-cucumber-preprocessor/steps';
import { clickElement, fillField, elementIsVisible, getAvailableElement, getSelector, forceClickElement, forceEnter} from '../../utils/driver';
import { FILTERS_PAGE as pageName} from '../../utils/pages-constants';
const addFilterButton = getSelector('addFilterButton', pageName);
const filterSuggestionList = getSelector('filterSuggestionList', pageName);
const filterOperatorList = getSelector('filterOperatorList', pageName);
const filterParams = getSelector('filterParams', pageName);
const saveFilterButton = getSelector('saveFilterButton', pageName);
const selectedOperator = getSelector('selectedOperator', pageName);
const selectedOperatorLabel= getSelector('selectedOperatorLabel', pageName);

When('The user adds a new filter', () => {
  elementIsVisible(addFilterButton);
  clickElement(addFilterButton);
  cy.wait(500);
  fillField(filterSuggestionList,'rule.level');
  forceEnter(filterSuggestionList);
  cy.wait(500);
  elementIsVisible(filterOperatorList);
  getAvailableElement(filterOperatorList);
  cy.wait(500);
  clickElement(filterOperatorList);
  cy.wait(500);
  elementIsVisible(selectedOperator);
  cy.wait(500);
  clickElement(selectedOperator);
  cy.wait(500);
  elementIsVisible(selectedOperatorLabel);
  elementIsVisible(filterParams);
  cy.wait(500);
  forceClickElement(filterParams);
  cy.removeAllListeners(500);
  fillField(filterParams,'7');
  clickElement(saveFilterButton);
});
